# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class RequestHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEncode = channel.unary_unary(
                '/RequestHandler/GetEncode',
                request_serializer=service__pb2.sourceImage.SerializeToString,
                response_deserializer=service__pb2.processedAndPrediction.FromString,
                )


class RequestHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEncode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequestHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEncode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncode,
                    request_deserializer=service__pb2.sourceImage.FromString,
                    response_serializer=service__pb2.processedAndPrediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RequestHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RequestHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEncode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RequestHandler/GetEncode',
            service__pb2.sourceImage.SerializeToString,
            service__pb2.processedAndPrediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
